Introduce new HOSTDIR, e.g. for python running on the build machine
Sometimes it is necessary to compile software needed by other packages
but running on the host machine, e.g. python. So we need a directory
to install those software in. It will not be copied to the target. Add the
bin directory to PATH and also set PYTHONPATH to the lib directory of
HOSTDIR as Python is one of the first packages which needs this.

diff --git a/scripts/build/lire_build b/scripts/build/lire_build
--- a/scripts/build/lire_build
+++ b/scripts/build/lire_build
@@ -83,13 +83,21 @@ mkdir -p "$LIRE_INSTDIR"
 echo "[OK]"
 
 #
-# copy $LIRE_INSTDIR/sys-root from toolchain
+# copy $LIRE_INSTDIR/sys-root from toolchain, create LIRE_HOSTDIR and set PYTHONPATH
 #
 if [ "$CONFIG_LIRE_CROSS_COMPILE" == "y" ]; then
     echo -n " Copy toolchain's sys-root ... "
     cp -a "$CONFIG_LIRE_TOOLCHAIN_PARENT_DIR/$CONFIG_LIRE_TARGET_TUPLE/$CONFIG_LIRE_TARGET_TUPLE/sys-root" "$LIRE_INSTDIR"
     [ $? -gt 0 ] && { echo "[FAILED]"; exit 1; }
     echo "[OK]"
+
+    echo -n " Creating LIRE hostdir ... "
+    mkdir -p "$LIRE_HOSTDIR"
+    [ $? -gt 0 ] && { echo "[FAILED]"; exit 1; }
+    echo "[OK]"
+
+    export PATH=${LIRE_HOSTDIR}/bin:$PATH
+    export PYTHONPATH=${LIRE_HOSTDIR}/lib
 fi
 
 #
